// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutView: typeof import('./../views/AboutView.vue')['default']
    Button: typeof import('vue-devui')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    HomeView: typeof import('./../views/HomeView.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    Welcome: typeof import('./../components/Welcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
